Repository Pipeline3/pipeline-book, pull requests merged in 2019-11, with the labels that each got.

#2 충돌 테스트
  README.md
Labels: good first issue

#3 [env] - add a PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#4 [merge] - PR template merge master to develop
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#5 PipelineBook 초안 작성
  .gitignore
  .storybook/addons.js
  .storybook/config.js
  .storybook/presets.js
  .storybook/webpack.config.js
  package-lock.json
  package.json
  rollup.config.js
  src/Button/Button.stories.tsx
  src/Button/Button.tsx
  src/ButtonGroup/ButtonGroup.stories.tsx
  src/ButtonGroup/ButtonGroup.tsx
  src/Bye/Bye.js
  src/Bye/Bye.stories.mdx
  src/Dialog/Dialog.stories.tsx
  src/Dialog/Dialog.tsx
  src/Hello/Hello.mdx
  src/Hello/Hello.stories.tsx
  src/Hello/Hello.tsx
  src/Icon/Icon.stories.tsx
  src/Icon/Icon.tsx
  src/Icon/svg/back.svg
  src/Icon/svg/download.svg
  src/Icon/svg/edit.svg
  src/Icon/svg/heart.svg
  src/Icon/svg/index.ts
  src/Icon/svg/reload.svg
  src/Icon/svg/settings.svg
  src/Icon/svg/upload.svg
  src/index.ts
  src/typings.d.ts
  stories/0-Welcome.stories.js
  stories/1-Button.stories.js
  tsconfig.json
  yarn.lock
Labels: enhancement
